name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - Aws_deploy  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Process SSH Key
      run: echo "${{ secrets.SERVER_SSH_KEY }}" | awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' > processed_key.pem
      shell: bash

    - name: Add Processed SSH Key to Agent
      run: |
        eval "$(ssh-agent -s)"
        chmod 400 processed_key.pem
        ssh-add processed_key.pem

    - name: Diagnostic SSH into EC2
      run: ssh -v ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "echo 'SSH connection successful'"

    - name: Deploy to EC2
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "\
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash && \
        export NVM_DIR=~/.nvm && \
        [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" && \
        nvm install node && \
        npm install -g pm2 && \
        cd /path/to/app && \
        git pull && \
        npm install && \
        pm2 restart all || pm2 start app.js"